collections:
  authors:
    output: true
  bio1101:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "bio1101"
    values:
      layout: "chapitre"
  - scope:
      path: ""
      type: "bio3150"
    values:
      layout: "chapitre"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag