collections:
  authors:
    output: true
  bio1101:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
      mathjax: true
  - scope:
      path: ""
      type: "bio1101"
    values:
      layout: "chapitre"
      mathjax: true
  - scope:
      path: ""
      type: "bio3150"
    values:
      layout: "chapitre"
      mathjax: true
  - scope:
      path: ""
    values:
      layout: "default"
      mathjax: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

remote_theme: pmarsceill/just-the-docs

theme: "just-the-docs"